### ISSUE TITLE
Emprunt groupés

### ISSUE THREAD

**Issue by Cesare90** [Toysurusse/Projet10#3]
Le client souhaite donner aux utilisateurs du site la possibilité d'emprunter plusieurs livres à la fois.

**Comment by Toysurusse** [comment]
Le panier permet d'enregistrer plusieurs locations de livre à la fois.

Le panier est constitué par une ArrayList permettant d'enregistrer une liste de livres à louer. La fonction rentbook() de la classe action.privacy.Rent.java permet d'enregistrer la location des livres mis au panier.

Les utilisateurs peuvent donc enregistrer plusieurs livres en une seule fois.
